
package com.example.feign.service;

import com.example.feign.service.impl.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsHelloImpl", targetNamespace = "http://impl.service.feign.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsHelloImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.feign.example.com/", className = "com.example.feign.service.impl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.feign.example.com/", className = "com.example.feign.service.impl.SayHelloResponse")
    @Action(input = "http://impl.service.feign.example.com/WsHelloImpl/sayHelloRequest", output = "http://impl.service.feign.example.com/WsHelloImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
