
package com.example.feign.service.impl;

import com.example.feign.service.WsHelloImpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsHelloImplService", targetNamespace = "http://impl.service.feign.example.com/", wsdlLocation = "http://localhost/wshello?wsdl")
public class WsHelloImplService
    extends Service
{

    private final static URL WSHELLOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSHELLOIMPLSERVICE_EXCEPTION;
    private final static QName WSHELLOIMPLSERVICE_QNAME = new QName("http://impl.service.feign.example.com/", "WsHelloImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wshello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSHELLOIMPLSERVICE_WSDL_LOCATION = url;
        WSHELLOIMPLSERVICE_EXCEPTION = e;
    }

    public WsHelloImplService() {
        super(__getWsdlLocation(), WSHELLOIMPLSERVICE_QNAME);
    }

    public WsHelloImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSHELLOIMPLSERVICE_QNAME, features);
    }

    public WsHelloImplService(URL wsdlLocation) {
        super(wsdlLocation, WSHELLOIMPLSERVICE_QNAME);
    }

    public WsHelloImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSHELLOIMPLSERVICE_QNAME, features);
    }

    public WsHelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsHelloImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsHelloImpl
     */
    @WebEndpoint(name = "WsHelloImplPort")
    public WsHelloImpl getWsHelloImplPort() {
        return super.getPort(new QName("http://impl.service.feign.example.com/", "WsHelloImplPort"), WsHelloImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsHelloImpl
     */
    @WebEndpoint(name = "WsHelloImplPort")
    public WsHelloImpl getWsHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.feign.example.com/", "WsHelloImplPort"), WsHelloImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSHELLOIMPLSERVICE_EXCEPTION!= null) {
            throw WSHELLOIMPLSERVICE_EXCEPTION;
        }
        return WSHELLOIMPLSERVICE_WSDL_LOCATION;
    }

}
